#!/bin/bash

# Setup script for local development with Azure SQL
# This configures your local environment to use Azure SQL instead of SQLite

set -e

RESOURCE_GROUP="babe-fight-rg"
SQL_SERVER="babefight-sql-1766424549"
SQL_SERVER_FQDN="${SQL_SERVER}.database.windows.net"
DEV_DB_NAME="babefightdb-dev"
PROD_DB_NAME="babefightdb"

echo "🚀 Local Azure SQL Development Setup"
echo "===================================="
echo ""

# Check if Azure CLI is installed
if ! command -v az &> /dev/null; then
    echo "❌ Azure CLI is not installed"
    echo "Install from: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli"
    exit 1
fi

# Check if logged in
echo "Checking Azure login status..."
if ! az account show &> /dev/null; then
    echo "❌ Not logged in to Azure"
    echo "Run: az login"
    exit 1
fi

echo "✅ Azure CLI authenticated"
echo ""

# Get current public IP
echo "Getting your public IP address..."
MY_IP=$(curl -s https://api.ipify.org)
echo "Your IP: $MY_IP"
echo ""

# Ask which database to use
echo "Which database do you want to use for local development?"
echo "1) Create new development database (babefightdb-dev) - RECOMMENDED"
echo "2) Use production database (babefightdb) - CAREFUL: Shared with production!"
echo ""
read -p "Enter choice (1 or 2): " db_choice

if [ "$db_choice" == "1" ]; then
    DB_NAME=$DEV_DB_NAME
    echo ""
    echo "📦 Creating development database: $DB_NAME"
    
    # Check if dev database exists
    if az sql db show --resource-group $RESOURCE_GROUP --server $SQL_SERVER --name $DB_NAME &> /dev/null; then
        echo "⚠️  Development database already exists"
        read -p "Delete and recreate? (yes/no): " recreate
        if [ "$recreate" == "yes" ]; then
            echo "Deleting existing database..."
            az sql db delete --resource-group $RESOURCE_GROUP --server $SQL_SERVER --name $DB_NAME --yes
            echo "Creating new database..."
            az sql db create \
                --resource-group $RESOURCE_GROUP \
                --server $SQL_SERVER \
                --name $DB_NAME \
                --service-objective Basic \
                --backup-storage-redundancy Local
            echo "✅ Development database created"
        fi
    else
        echo "Creating development database..."
        az sql db create \
            --resource-group $RESOURCE_GROUP \
            --server $SQL_SERVER \
            --name $DB_NAME \
            --service-objective Basic \
            --backup-storage-redundancy Local
        echo "✅ Development database created"
    fi
elif [ "$db_choice" == "2" ]; then
    DB_NAME=$PROD_DB_NAME
    echo ""
    echo "⚠️  WARNING: You will be using the PRODUCTION database!"
    echo "Any changes you make will affect production data."
    read -p "Are you sure? (yes/no): " confirm
    if [ "$confirm" != "yes" ]; then
        echo "❌ Cancelled"
        exit 1
    fi
else
    echo "❌ Invalid choice"
    exit 1
fi

echo ""

# Add firewall rule
RULE_NAME="LocalDev-$(whoami)-$(date +%Y%m%d)"
echo "🔒 Adding firewall rule: $RULE_NAME"

# Check if rule exists
if az sql server firewall-rule show \
    --resource-group $RESOURCE_GROUP \
    --server $SQL_SERVER \
    --name "$RULE_NAME" &> /dev/null; then
    echo "Updating existing firewall rule..."
    az sql server firewall-rule update \
        --resource-group $RESOURCE_GROUP \
        --server $SQL_SERVER \
        --name "$RULE_NAME" \
        --start-ip-address $MY_IP \
        --end-ip-address $MY_IP
else
    echo "Creating new firewall rule..."
    az sql server firewall-rule create \
        --resource-group $RESOURCE_GROUP \
        --server $SQL_SERVER \
        --name "$RULE_NAME" \
        --start-ip-address $MY_IP \
        --end-ip-address $MY_IP
fi

echo "✅ Firewall rule configured"
echo ""

# Get SQL admin password
echo "📝 SQL Server Configuration"
echo "Server: $SQL_SERVER_FQDN"
echo "Database: $DB_NAME"
echo "User: sqladmin"
echo ""
echo "⚠️  You need the SQL admin password to continue"
echo "Get it from:"
echo "  - Azure Portal > SQL Server > Settings"
echo "  - Ask team member who configured the server"
echo "  - Or reset it with: az sql server update --admin-password 'NewPassword'"
echo ""
read -sp "Enter SQL admin password: " SQL_PASSWORD
echo ""
echo ""

# Create .env file
echo "📝 Creating backend/.env file..."
cat > backend/.env << EOF
# Azure SQL Database Connection (Local Development)
# Generated by setup-local-azure-sql.sh on $(date)
DB_TYPE=mssql
DB_SERVER=$SQL_SERVER_FQDN
DB_NAME=$DB_NAME
DB_USER=sqladmin
DB_PASSWORD=$SQL_PASSWORD
DB_ENCRYPT=true

# Server Configuration
PORT=8080
NODE_ENV=development

# Note: Never commit this file to git!
# The .env file is in .gitignore
EOF

echo "✅ Created backend/.env"
echo ""

# Test connection
echo "🧪 Testing database connection..."
cd backend

# Create test script
cat > test-connection.js << 'EOF'
require('dotenv').config();
const sql = require('mssql');

const config = {
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  server: process.env.DB_SERVER,
  database: process.env.DB_NAME,
  options: {
    encrypt: true,
    trustServerCertificate: false,
    connectTimeout: 10000,
  },
};

console.log('Connecting to:', process.env.DB_SERVER);
console.log('Database:', process.env.DB_NAME);
console.log('User:', process.env.DB_USER);
console.log('');

sql.connect(config)
  .then(pool => {
    console.log('✅ Successfully connected to Azure SQL Database!');
    console.log('');
    return pool.request().query('SELECT @@VERSION AS Version');
  })
  .then(result => {
    console.log('SQL Server Version:');
    console.log(result.recordset[0].Version);
    console.log('');
    process.exit(0);
  })
  .catch(err => {
    console.error('❌ Connection failed:');
    console.error(err.message);
    console.error('');
    console.error('Troubleshooting:');
    console.error('1. Check firewall rules: az sql server firewall-rule list --resource-group babe-fight-rg --server ' + process.env.DB_SERVER.split('.')[0]);
    console.error('2. Verify password is correct');
    console.error('3. Ensure your IP (' + process.env.DB_SERVER + ') is whitelisted');
    process.exit(1);
  });
EOF

# Run test
node test-connection.js
TEST_RESULT=$?

# Cleanup test script
rm test-connection.js

cd ..

if [ $TEST_RESULT -eq 0 ]; then
    echo ""
    echo "🎉 Setup Complete!"
    echo "================="
    echo ""
    echo "✅ Your local environment is configured to use Azure SQL"
    echo "✅ Database: $DB_NAME"
    echo "✅ Connection tested successfully"
    echo ""
    echo "Next steps:"
    echo "1. Start development server: bash scripts/run-local.sh"
    echo "2. Frontend will be at: http://localhost:5173"
    echo "3. Backend API at: http://localhost:8080"
    echo ""
    echo "📚 Documentation: docs/setup/LOCAL_AZURE_SQL_SETUP.md"
    echo ""
    echo "⚠️  Remember to test all schema changes locally before deploying!"
else
    echo ""
    echo "❌ Connection test failed"
    echo "Check the error message above and try again"
    echo ""
    echo "Common issues:"
    echo "- Wrong password: Get from Azure Portal or reset it"
    echo "- Firewall: Your IP may have changed, run this script again"
    echo "- Database not ready: Wait a minute and try again"
    exit 1
fi
